### ISSUE TITLE
neuronicworks, toronto

### ISSUE THREAD

**Issue by mmrobert** [STMicroelectronics-CentralLabs/BlueSTSDK_GUI_Android#1]
Hi, there, I am working in NeuronicWorks, Toronto, as a mobile developer.

Now I am using your development kit for your blue tooth (chip) device. 

If it is possible for you to combine "BlueSTSDK_Android" and BlueSTSDK_GUI_Android" into one git repo, so I can use "import module" from Android Studio to import the 2 modules.

Thanks very much.

Boqian Cheng

**Comment by GiovanniVisentini** [comment]
Hi Boqian,

there are any problems to import 2 modules?

the BlueSTSDK is think to work only with the ble and leave the user the freedom to implement the gui as it preferrer..
instead the BlueSTSDK_Gui include extension build on top of the BlueSTSDK and some utility activity for the gui..
I splatted the 2 library because someone is interested only to the BLE functionality and doesn't want to include stuff that are not needed.. 

Thanks
Giovanni

**Comment by mmrobert** [comment]
Hi, Giovanni,

Thanks for replying.

Now I import "BlueSTSDK", "BlueSTSDK_Gui" and "BlueMS" into my Android as modules.

But as I run, "error: element value must be a constant expression" coming up, for:
@DemoDescriptionAnnotation(name="Beamforming",iconRes= R.drawable.beamforming_icon,

and this happens for each R.drawable in BlueMS module.

So any suggestion?

Thank you very much and have a great weekend.

Boqian

**Comment by GiovanniVisentini** [comment]
Hi Boqian,

the annotation are processed at compile time, and they need to access to constant field.
the resource file in a module is not constant since it will be merged with the application resource file, and the values could change.

so basically the BlueMS repository can not be imported as a module.
at the end it contains the application code, it is not a library.

in my opinion you have 2 options:
- develop you application as a fork of the BlueMS 
- avoid to import the BlueMS module, and copy in your app the demos page that you care. At the end all the code that are not demo specific, should be included into the BlueSTSDK_Gui, so you shouldn't loose any functionality.

Best Regards
Giovanni

**Comment by mmrobert** [comment]
Hi, Giovanni,

Thanks a lot.

I am going to use the option 2 you suggested (importing modules BlueSTSDK and BlueSTSDK_Gui).

When I clone BlueSTSDK_Gui to my local, and then try to import the module from Android Studio, and the module is not showing and can not be done.

So now I clone whole app STBlueMS_Android to my local, then in Android Studio to import the module BlueMS (not the app project) into my app, this way the dependent modules BlueSTSDK and BlueSTSDK_Android are imported. Finally I delete the module BlueMS, and the modules BlueSTSDK and BlueSTSDK_Android are not deleted and staying.

Is this the right way to import the modules BlueSTSDK and BlueSTSDK_Android?

Have a good one.

Best regards,

Boqian

**Comment by mmrobert** [comment]
Thanks
